---
spring:
  profiles: local
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: # need to provide jdbc url string
    username: # database username
    password: # database password