---
spring:
  profiles: local
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: # need to provide jdbc url string
    username: # database username
    password: # database password
  app:
    version: 1.0

swagger:
  title: Basket Ball Checkin App REST Api
  description: REST Api Endpoints
  contact:
    name: Phouthasak Douanglee
    website: phouthasak.com
    email: jphouthasakdouanglee@gmail.com