---
spring:
  main:
    allow-bean-definition-overriding: true
  profiles: local
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/basketballcheckin?autoReconnect=true&useSSL=false&serverTimezone=EST&useLegacyDatetimeCode=false
      username: phouthasak
      password: UTrockets95
  servlet:
    multipart:
      max-file-size: 10MB
      file-size-threshold: 2KB
      max-request-size: 20MB
      enabled: true
  app:
    version: 1.0

swagger:
  title: Basket Ball Checkin App REST Api
  description: REST Api Endpoints
  contact:
    name: Phouthasak Douanglee
    website: http://phouthasak.com
    email: jphouthasakdouanglee@gmail.com