package com.phouthasak.webapp.basketballCheckin.util;

public interface Constants {
    String AUDIT_ACTION_TYPE_CREATE_PLAYER = "CREATE_PLAYER";
    String AUDIT_ACTION_TYPE_CREATE_EVENT = "CREATE_EVENT";
    String AUDIT_ACTION_TYPE_PLAYER_CHECKIN_NEW = "PLAYER_CHECKIN_NEW";
    String AUDIT_ACTION_TYPE_NON_PLAYER_CHECKIN_NEW = "NON_PLAYER_CHECKIN_NEW";
    String AUDIT_ACTION_TYPE_PLAYER_CHECKIN_UPDATE = "PLAYER_CHECKIN_UPDATE";
    String AUDIT_ACTION_TYPE_NON_PLAYER_CHECKIN_UPDATE = "NON_PLAYER_CHECKIN_UPDATE";
    String AUDIT_ACTION_TYPE_EVENT_DELETE = "DELETE_EVENT";
}
